from bees import profiler as p
"Possible task states for instances.\n\nCompute instance task states represent what is happening to the instance at the\ncurrent moment. These tasks can be generic, such as 'spawning', or specific,\nsuch as 'block_device_mapping'. These task states allow for a better view into\nwhat an instance is doing and should be displayed to users/administrators as\nnecessary.\n\n"
from nova.objects import fields
SCHEDULING = fields.InstanceTaskState.SCHEDULING
BLOCK_DEVICE_MAPPING = fields.InstanceTaskState.BLOCK_DEVICE_MAPPING
NETWORKING = fields.InstanceTaskState.NETWORKING
SPAWNING = fields.InstanceTaskState.SPAWNING
IMAGE_SNAPSHOT = fields.InstanceTaskState.IMAGE_SNAPSHOT
IMAGE_SNAPSHOT_PENDING = fields.InstanceTaskState.IMAGE_SNAPSHOT_PENDING
IMAGE_PENDING_UPLOAD = fields.InstanceTaskState.IMAGE_PENDING_UPLOAD
IMAGE_UPLOADING = fields.InstanceTaskState.IMAGE_UPLOADING
IMAGE_BACKUP = fields.InstanceTaskState.IMAGE_BACKUP
UPDATING_PASSWORD = fields.InstanceTaskState.UPDATING_PASSWORD
RESIZE_PREP = fields.InstanceTaskState.RESIZE_PREP
RESIZE_MIGRATING = fields.InstanceTaskState.RESIZE_MIGRATING
RESIZE_MIGRATED = fields.InstanceTaskState.RESIZE_MIGRATED
RESIZE_FINISH = fields.InstanceTaskState.RESIZE_FINISH
RESIZE_REVERTING = fields.InstanceTaskState.RESIZE_REVERTING
RESIZE_CONFIRMING = fields.InstanceTaskState.RESIZE_CONFIRMING
REBOOTING = fields.InstanceTaskState.REBOOTING
REBOOT_PENDING = fields.InstanceTaskState.REBOOT_PENDING
REBOOT_STARTED = fields.InstanceTaskState.REBOOT_STARTED
REBOOTING_HARD = fields.InstanceTaskState.REBOOTING_HARD
REBOOT_PENDING_HARD = fields.InstanceTaskState.REBOOT_PENDING_HARD
REBOOT_STARTED_HARD = fields.InstanceTaskState.REBOOT_STARTED_HARD
PAUSING = fields.InstanceTaskState.PAUSING
UNPAUSING = fields.InstanceTaskState.UNPAUSING
SUSPENDING = fields.InstanceTaskState.SUSPENDING
RESUMING = fields.InstanceTaskState.RESUMING
POWERING_OFF = fields.InstanceTaskState.POWERING_OFF
POWERING_ON = fields.InstanceTaskState.POWERING_ON
RESCUING = fields.InstanceTaskState.RESCUING
UNRESCUING = fields.InstanceTaskState.UNRESCUING
REBUILDING = fields.InstanceTaskState.REBUILDING
REBUILD_BLOCK_DEVICE_MAPPING = fields.InstanceTaskState.REBUILD_BLOCK_DEVICE_MAPPING
REBUILD_SPAWNING = fields.InstanceTaskState.REBUILD_SPAWNING
MIGRATING = fields.InstanceTaskState.MIGRATING
DELETING = fields.InstanceTaskState.DELETING
SOFT_DELETING = fields.InstanceTaskState.SOFT_DELETING
RESTORING = fields.InstanceTaskState.RESTORING
SHELVING = fields.InstanceTaskState.SHELVING
SHELVING_IMAGE_PENDING_UPLOAD = fields.InstanceTaskState.SHELVING_IMAGE_PENDING_UPLOAD
SHELVING_IMAGE_UPLOADING = fields.InstanceTaskState.SHELVING_IMAGE_UPLOADING
SHELVING_OFFLOADING = fields.InstanceTaskState.SHELVING_OFFLOADING
UNSHELVING = fields.InstanceTaskState.UNSHELVING
ALLOW_REBOOT = [None, REBOOTING, REBOOT_PENDING, REBOOT_STARTED, RESUMING, REBOOTING_HARD, UNPAUSING, PAUSING, SUSPENDING]
soft_reboot_states = (REBOOTING, REBOOT_PENDING, REBOOT_STARTED)
hard_reboot_states = (REBOOTING_HARD, REBOOT_PENDING_HARD, REBOOT_STARTED_HARD)
resizing_states = (RESIZE_PREP, RESIZE_MIGRATING, RESIZE_MIGRATED, RESIZE_FINISH)
rebuild_states = (REBUILDING, REBUILD_BLOCK_DEVICE_MAPPING, REBUILD_SPAWNING)